windowrule = workspace 4, match:title ^(.*Blender.*)$
windowrule = workspace 5, match:title ^(.*Discord.*)$
windowrule = workspace 5, match:title ^(.*Signal.*)$
windowrule = workspace 9, match:title ^(.*Parsec.*)$

$sizeWide = size (monitor_w*0.5) (monitor_h*0.5)
$sizeHigh = size (monitor_w*0.3) (monitor_h*0.8)
$sizeThic = size (monitor_w*0.6) (monitor_h*0.7)

windowrule = float on, center on, $sizeThic, match:class popup.app.thic
windowrule = float on, center on, $sizeHigh, match:class popup.app.high

windowrule = float on, center on, $sizeHigh, match:class blender, match:title Preferences
windowrule = float on, center on, $sizeWide, match:class blender, match:title File Browser
windowrule = float on, center on, $sizeWide, match:class blender, match:title Image Editor

windowrule = float on, match:class one.alynx.showmethekey
windowrule = float on, workspace 4, no_initial_focus on, move 40 1190, size 600 80, match:class showmethekey-gtk

windowrule = float on, center on, match:class ^(Matplotlib)$
windowrule = center on, match:class discord, match:title Discord Updater

windowrule = no_shadow on, match:float 0

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
