format = """
[╭── ](bold meh)\
$jobs\
$hostname\
$directory\
$git_branch\
$git_status\
$nix_shell\
\n[╰─](bold meh)\
$character
"""

palette = "onyx"

[jobs]
style = "bold red"

[directory]
truncation_length = 3
truncation_symbol = "../"
style = "text"

[git_branch]
symbol = " "
style = "text"
format = '[on](meh) [$symbol$branch]($style) '

[git_status]
disabled = true
style = "meh"

[nix_shell]
symbol = "󱄅 "
style = "text"
format = '[via](meh) [$symbol$name]($style) '

[character]
success_symbol = "[λ](bold blue)"
error_symbol = "[λ](bold red)"

[hostname]
style = "blue"
format = '[$hostname]($style) [in](meh) '

[palettes.onyx]
deep = "#1a1a1a"
base = "#202020"
smol = "#383838"
dim = "#525252"
meh = "#8b8b8b"
text = "#c8c8c8"
red = "#fd7eaa"
peach = "#deb39c"
green = "#97cbb8"
blue = "#96c6dd"
purp = "#bcb8e2"
aqua = "#b2c4d0"
