require("plugins.onyx")

require("plugins.blink")
require("plugins.lazygit")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.oil")
require("plugins.telescope")
require("plugins.todo")
require("plugins.toggler")
require("plugins.treesitter")
require("plugins.ui")
require("plugins.yazi")
