disableStartupPopups: true

gui:

  theme:
    defaultFgColor:
      - "#c8c8c8"
    activeBorderColor:
      - "#c8c8c8"
      - bold
    inactiveBorderColor:
      - "#525252"
    searchingActiveBorderColor:
      - green
      - bold
    optionsTextColor:
      - "#525252"
    selectedLineBgColor:
      - reverse
    inactiveViewSelectedLineBgColor:
      - "#383838"

  authorColors:
    "aeraglyx": "#c8c8c8"
    "*":        "#525252"

  scrollHeight: 1
  nerdFontsVersion: "3"
  showFileIcons: false
  showBottomLine: false
  showRootItemInFileTree: false
  sidePanelWidth: 0.4
